version: '3'

services:
  app:
    build: .
    ports:
      - 3333:3333
    volumes:
      - .:/home/node/app

  db:
    image: mysql:8.0.30-debian
    ports: 
      - 3356:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: job_board
